name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    environment: test-env
    env: 
      job_name: test
    runs-on: ubuntu-latest
    steps:
      - name: my env name
        run: echo "Job name is ${{ env.job_name }} running on workflow with env name ${{ env.NODE_ENV }}"
      - name: print secret
        run: echo "My secret is ${{ secrets.SECRET_VARIABLE }}"
      - name: print env specific secret
        run: echo "My env specific secret is ${{ secrets.ENV_NAME }} AND my env variable is ${{ vars.ENV_VARIABLE_NAME }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        working-directory: "02 Starting Project"
        run: npm ci --include=dev
      - name: Lint code
        working-directory: "02 Starting Project"
        run: npm run lint
      - name: Test code
        working-directory: "02 Starting Project"
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        working-directory: "02 Starting Project"
        run: npm ci --include=dev
      - name: Build website
        working-directory: "02 Starting Project"
        run: npm run build
      - name: Publish JS file name
        id: publish
        working-directory: "02 Starting Project"
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        working-directory: "02 Starting Project"
        run: echo "Deploying..."
