name: Deploy-js-project


on: 
  push :
    branches: 
        - main
  workflow_dispatch:
    
jobs:
  test-js:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        working-directory: "02 Starting Project"
        run: npm ci

      - name: run tests
        working-directory: "02 Starting Project"
        run: npm test
  deploy:
    needs: test-js # This ensures that the deploy job runs only after the test-js job has completed successfully by default, the deploy job will run in parallel with test-js
    runs-on: ubuntu-latest
    steps:
       - name: Get code
         uses: actions/checkout@v4
       - name: Use Node.js 18
         uses: actions/setup-node@v4
         with: 
                node-version: 18    
       - name: Install dependencies
         working-directory: "02 Starting Project"
         run: npm ci
       - name: Build project
         working-directory: "02 Starting Project"
         run: npm run build
       - name: Deploy
         run: echo "Deploying project..." # Replace this with your actual deployment command   
