name: test-js-project

on: push

jobs:
  test-js:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        working-directory: "02 Starting Project"
        run: npm ci

      - name: run tests
        working-directory: "02 Starting Project"
        run: npm test
       
